/* 
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Blocks : This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Blocks {
}

impl Blocks {
  /// This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace.
  pub fn new() -> Blocks {
    Blocks {
    }
  }

}



